 INSERT INTO msfo.CORSA_LOG(
	REPORTID, USERNAME, SESSIONTIME, LOAD_FILE, TOCOMPARE, SESSIONTIME_PREV, STATUS, DURATION, ACTUAL_MAN, ACTUAL_AUT)
	VALUES ($1, $2, now(),$3,0,(select max(l.SESSIONTIME) from msfo.CORSA_log l where USERNAME =  $4  and REPORTID = $5 and status='Ок')
    , $6, null, 0, 0)
	RETURNING LOAD_ID;